# Generated by Django 4.1.7 on 2023-03-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maqola',
            name='rasm',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
